"""auto update

Revision ID: 318a016c2b87
Revises: 5d525de98a06
Create Date: 2026-04-11 15:11:01.415096

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '318a016c2b87'
down_revision: Union[str, Sequence[str], None] = '5d525de98a06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('design_files',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(), nullable=False),
    sa.Column('object_key', sa.String(), nullable=False),
    sa.Column('file_type', sa.String(), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('is_source', sa.Boolean(), nullable=True),
    sa.Column('is_final', sa.Boolean(), nullable=True),
    sa.Column('uploaded_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_design_files_id'), 'design_files', ['id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_table('team_members',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('member_email', sa.String(), nullable=False),
    sa.Column('member_name', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_team_members_id'), 'team_members', ['id'], unique=False)
    op.add_column('brands', sa.Column('logo_key', sa.String(), nullable=True))
    op.add_column('brands', sa.Column('primary_color', sa.String(), nullable=True))
    op.add_column('brands', sa.Column('secondary_color', sa.String(), nullable=True))
    op.add_column('brands', sa.Column('fonts', sa.String(), nullable=True))
    op.add_column('brands', sa.Column('website', sa.String(), nullable=True))
    op.add_column('brands', sa.Column('industry', sa.String(), nullable=True))
    op.add_column('brands', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('brands', 'logo_url')
    op.drop_column('brands', 'color_secondary')
    op.drop_column('brands', 'color_primary')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('brands', sa.Column('color_primary', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('brands', sa.Column('color_secondary', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('brands', sa.Column('logo_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('brands', 'updated_at')
    op.drop_column('brands', 'industry')
    op.drop_column('brands', 'website')
    op.drop_column('brands', 'fonts')
    op.drop_column('brands', 'secondary_color')
    op.drop_column('brands', 'primary_color')
    op.drop_column('brands', 'logo_key')
    op.drop_index(op.f('ix_team_members_id'), table_name='team_members')
    op.drop_table('team_members')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_design_files_id'), table_name='design_files')
    op.drop_table('design_files')
    # ### end Alembic commands ###